clean

diff --git a/src/doasedit b/src/doasedit
--- a/src/doasedit
+++ b/src/doasedit
@@ -1,19 +1,19 @@
 #!/bin/sh
 
-#-----------------------------------------------------------Check some errors
+#-----------------------------------------------------------Check some Errors
 
-ERR() {
+Err() {
 	printf '%s\n' "doasedit: $2" 1>&2
 	test $1 -gt 0 && exit $1
 }
 
-test `id -u` -eq 0 && ERR 2 'denied to run as root...'
+test `id -u` -eq 0 && Err 2 'denied to run as root...'
 
-test $# -ne 1 && ERR 2 "doesn't specify file..."
+test $# -ne 1 && Err 2 "no file was specify..."
 
-test -f "$1" || ERR 2 "$1 is a directory or doesn't exists..."
+test -f "$1" || Err 2 "'$1' is a directory or doesn't exists..."
 
-test -O "$1" -o -w "$1" && ERR 2 "$1 doesn't need root access..."
+test -O "$1" -o -w "$1" && Err 2 "'$1' doesn't need root access..."
 
 if test -r "$1"; then
 	Readable=1
@@ -22,9 +22,9 @@ else
 		printf '%b\n' "$Curline"
 	done <<-EOF
 
-		\rdoasedit() doesn't has permission to read \`$1\`
-		\rif continue you will need to type your password 3 times
-		\runless you have \`persist\` option in your /etc/doas.conf
+		\rdoasedit() doesn't has permission to read '$1'
+		\rif continue, you'll need to type password 3 times
+		\runless you have 'persist' option in '/etc/doas.conf'
 
 	EOF
 
@@ -37,7 +37,7 @@ else
 			Readable=0 ;;
 
 		*)
-			ERR 2 "unknown answer(s) $1..." ;;
+			Err 2 "unknown answer(s) '$1'..." ;;
 	esac
 fi
 
@@ -46,26 +46,29 @@ fi
 # Make random variables static
 TMPFILE="${TMPDIR:-/tmp}/doasedit-$SRANDOM"
 
-# Copy original file to tmp directory
-test $Readable -eq 1 && cp $1 $TMPFILE ||
-	{ while :; do doas cp $1 $TMPFILE && break; done
-	while :; do doas chown $USER $TMPFILE && break; done ;}
+# Copy original file to temp directory
+if test $Readable -eq 1; then
+	cp $1 $TMPFILE
+else
+	while :; do doas cp "$1" "$TMPFILE" && break; done
+	while :; do doas chown "$USER" "$TMPFILE" && break; done
+fi
 
-# Remove tmp file when exit
-trap 'rm -f $TMPFILE' EXIT
+# Remove temp file when exit
+trap 'rm -f "$TMPFILE"' EXIT
 
-test -w "$TMPFILE" || ERR 2 "$1 is write protected, aborted..."
+test -w "$TMPFILE" || Err 2 "'$1' is write protected, aborted..."
 
 #----------------------------------------------------------Start to edit the file
 
-# Edit tmp file
-${DOAS_EDITOR:-vi} $TMPFILE ||
-	ERR 2 '$DOAS_EDITOR is set to something that unusable...'
+# Edit temp file
+${DOAS_EDITOR:-vi} "$TMPFILE" ||
+	Err 2 '$DOAS_EDITOR is set to something that unusable...'
 
 # Don't do anything if file's content doesn't change
-cmp -s $1 $TMPFILE && ERR 1 "$1 doesn't change..."
+cmp -s "$1" "$TMPFILE" && Err 1 "'$1' doesn't change..."
 
 while :; do
 	# Break while loop only when user successfully type password
-	doas cp $TMPFILE $1 && break
+	doas cp "$TMPFILE" "$1" && break
 done
